name = "mbse"
version = "0.1.0"
defaultTargets = ["mbse", "Appendix3"]

[[lean_lib]]
name = "Mbse"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Appendix3"

[[lean_exe]]
name = "mbse"
root = "Main"
