import Mbse.WymoreRequirements

/-!
# The boundary temporal fragment of an input/output requirement

Every Wymore input/output requirement determines a characteristic boundary
property.  The property retains the required time scale, eligible input
trajectories, and the (possibly nondeterministic) relation from each eligible
input to its eligible outputs.  It drops only `OTR`, which is redundant for
satisfaction because an `InputOutputRequirement` proves that `OTR` is exactly
covered by `ER`.

This construction covers finite and infinite operational lengths, restricted
input sets, and nondeterministic eligible-output relations.  The functional
infinite construction below is only a convenience for readable examples.
-/

namespace IORTemporalFragment

open WymoreRequirements

/-- A state-free temporal property over complete boundary trajectories. -/
structure BoundaryFragment (IR OR : Type) where
  times : Set Time
  inputs : Set (ITZ IR)
  allows : ITZ IR → ITZ OR → Prop

/-- The characteristic boundary fragment generated by a Wymore IOR. -/
def ofIOR (R : InputOutputRequirement IR OR) : BoundaryFragment IR OR where
  times := TSR R
  inputs := R.itr
  allows f g := g ∈ R.er f

/--
Satisfaction of a boundary fragment by a discrete system.  This is the
assertional reading of Wymore's trajectory-extension satisfaction condition.
-/
def Satisfies {S IR OR : Type} (Z : DiscreteSystem S IR OR)
    (Φ : BoundaryFragment IR OR) (s0 : S) (T : Set Time) : Prop :=
  T.Nonempty ∧
  T ⊆ Φ.times ∧
  ∀ f ∈ Φ.inputs,
    ∀ h : ITZ IR, agreesOn h f Φ.times →
      ∃ g, Φ.allows f g ∧
        ∀ t ∈ T, generateOutputTrajectory Z s0 (liftInput h) t = some (g t)

/--
The characteristic fragment has the same satisfaction predicate as the IOR.
No determinism, horizon, or eligibility restriction is imposed.
-/
theorem satisfies_ofIOR_iff {S IR OR : Type} (Z : DiscreteSystem S IR OR)
    (R : InputOutputRequirement IR OR) (s0 : S) (T : Set Time) :
    Satisfies Z (ofIOR R) s0 T ↔ SatisfiesIOR Z R s0 T :=
  Iff.rfl

/-- A functional design packaged using boundary-fragment satisfaction. -/
structure AssertionalFunctionalDesign {IR OR : Type}
    (Φ : BoundaryFragment IR OR) where
  S : Type
  Z : DiscreteSystem S IR OR
  DSZ : S
  TSZ : Set Time
  satisfies : Satisfies Z Φ DSZ TSZ

/-- The assertional functionality space generated by a boundary fragment. -/
abbrev AFSR {IR OR : Type} (Φ : BoundaryFragment IR OR) :=
  AssertionalFunctionalDesign Φ

/--
Compiling an IOR into its characteristic boundary fragment gives a canonical
equivalence between the assertional and Wymore functionality spaces.
-/
def afsrEquivFSR (R : InputOutputRequirement IR OR) :
    AFSR (ofIOR R) ≃ FSR R where
  toFun d :=
    { S := d.S
      Z := d.Z
      DSZ := d.DSZ
      TSZ := d.TSZ
      satisfies := (satisfies_ofIOR_iff d.Z R d.DSZ d.TSZ).mp d.satisfies }
  invFun d :=
    { S := d.S
      Z := d.Z
      DSZ := d.DSZ
      TSZ := d.TSZ
      satisfies := (satisfies_ofIOR_iff d.Z R d.DSZ d.TSZ).mpr d.satisfies }
  left_inv d := by
    cases d
    rfl
  right_inv d := by
    cases d
    rfl

theorem afsr_nonempty_iff_fsr_nonempty (R : InputOutputRequirement IR OR) :
    Nonempty (AFSR (ofIOR R)) ↔ Nonempty (FSR R) :=
  (afsrEquivFSR R).nonempty_congr

/-- An infinite deterministic IOR induced by a pure boundary trajectory map. -/
def functionalIOR [Nonempty IR] (ψ : ITZ IR → ITZ OR) :
    InputOutputRequirement IR OR where
  olr := .infinite
  itr := Set.univ
  otr := Set.range ψ
  er := fun f => {ψ f}
  itr_nonempty := ⟨fun _ => Classical.choice inferInstance, Set.mem_univ _⟩
  otr_nonempty := by
    let f : ITZ IR := fun _ => Classical.choice inferInstance
    exact ⟨ψ f, f, rfl⟩
  er_subset := by
    intro f _ g hg
    rw [Set.mem_singleton_iff] at hg
    exact ⟨f, hg.symm⟩
  er_nonempty := by
    intro f _
    exact ⟨ψ f, Set.mem_singleton _⟩
  otr_from_er := by
    intro g hg
    rcases hg with ⟨f, rfl⟩
    exact ⟨f, Set.mem_univ _, Set.mem_singleton _⟩

/-- Complete satisfaction of a functional infinite IOR is its pointwise law. -/
theorem satisfies_functionalIOR_iff {S IR OR : Type} [Nonempty IR]
    (Z : DiscreteSystem S IR OR) (ψ : ITZ IR → ITZ OR) (s0 : S) :
    SatisfiesIOR Z (functionalIOR ψ) s0 Set.univ ↔
      ∀ f t, generateOutputTrajectory Z s0 (liftInput f) t = some (ψ f t) := by
  constructor
  · rintro ⟨_, _, hsat⟩ f t
    have hAgr : agreesOn f f (TSR (functionalIOR ψ)) := fun _ _ => rfl
    obtain ⟨g, hg, hout⟩ := hsat f (by simp [functionalIOR]) f hAgr
    have hgf : g = ψ f := by
      simpa [functionalIOR] using hg
    subst g
    exact hout t (Set.mem_univ _)
  · intro hout
    refine ⟨Set.univ_nonempty, by simp [functionalIOR, TSR, timeScale], ?_⟩
    intro f _ h hAgr
    have hhf : h = f := by
      funext t
      exact hAgr t (by simp [functionalIOR, TSR, timeScale])
    refine ⟨ψ f, by simp [functionalIOR], ?_⟩
    intro t _
    rw [hhf]
    exact hout f t

/-! ## A compact ladder of boundary laws -/

/-- Memoryless echo.  Its exact characteristic property is `G (y = x)`. -/
def echoOut (f : ITZ Bool) : ITZ Bool := f

/-- One-tick delay with a fixed initial output: `y 0 = init`, `G (X y = x)`. -/
def delayOut (init : Bool) (f : ITZ Bool) : ITZ Bool
  | 0 => init
  | t + 1 => f t

def echoIOR : InputOutputRequirement Bool Bool := functionalIOR echoOut

def delayIOR (init : Bool) : InputOutputRequirement Bool Bool :=
  functionalIOR (delayOut init)

theorem satisfies_echo_iff {S : Type} (Z : DiscreteSystem S Bool Bool) (s0 : S) :
    SatisfiesIOR Z echoIOR s0 Set.univ ↔
      ∀ f t, generateOutputTrajectory Z s0 (liftInput f) t = some (f t) := by
  simpa [echoIOR, echoOut] using
    satisfies_functionalIOR_iff (IR := Bool) (OR := Bool) Z echoOut s0

theorem satisfies_delay_iff {S : Type} (Z : DiscreteSystem S Bool Bool)
    (s0 : S) (init : Bool) :
    SatisfiesIOR Z (delayIOR init) s0 Set.univ ↔
      ∀ f t, generateOutputTrajectory Z s0 (liftInput f) t =
        some (delayOut init f t) :=
  satisfies_functionalIOR_iff (IR := Bool) (OR := Bool) Z (delayOut init) s0

end IORTemporalFragment
