import Mbse.PartialDynamicsHomFragment

/-!
# A solver-discovered conformance map, machine-checked

Generated by `scripts/phi_dyn_solver.py --emit-lean` for the `tape-vs-instrumented` instance; do not edit by
hand.  The two systems are the reference and the candidate of that instance, re-indexed by `Fin`, and
`hS`, `hI`, `hO` are the maps the SAT solver returned.  Every law of Definition 4.3 is then checked
by the kernel with `decide`, so the solver is not being trusted: it proposes, Lean verifies.
-/

namespace SolverWitness

open Homomorphism PartialDynamicsHomFragment

/-! ## The reference, as a table over `Fin 8` -/

def specNext : Fin 8 → Fin 4 → Fin 8 :=
  fun x t => [
    0, 0, 1, 5,
    1, 1, 1, 3,
    2, 2, 3, 7,
    3, 3, 1, 3,
    4, 4, 1, 5,
    5, 5, 5, 7,
    6, 6, 3, 7,
    7, 7, 5, 7
  ].getD (x.val * 4 + t.val) 0

def specOut : Fin 8 → Option (Fin 2) :=
  fun i => [
    some 0, some 0, some 0, some 1, some 1, some 0,
    some 1, some 1
  ].getD i.val none

/-! ## The candidate, as a table over `Fin 16` -/

def implNext : Fin 16 → Fin 4 → Fin 16 :=
  fun x t => [
    0, 1, 3, 11,
    1, 0, 2, 10,
    2, 3, 3, 7,
    3, 2, 2, 6,
    4, 5, 7, 15,
    5, 4, 6, 14,
    6, 7, 3, 7,
    7, 6, 2, 6,
    8, 9, 3, 11,
    9, 8, 2, 10,
    10, 11, 11, 15,
    11, 10, 10, 14,
    12, 13, 7, 15,
    13, 12, 6, 14,
    14, 15, 11, 15,
    15, 14, 10, 14
  ].getD (x.val * 4 + t.val) 0

def implOut : Fin 16 → Option (Fin 2) :=
  fun i => [
    some 0, some 0, some 0, some 0, some 0, some 0,
    some 1, some 1, some 1, some 1, some 0, some 0,
    some 1, some 1, some 1, some 1
  ].getD i.val none

/-- Index a driven or autonomous tick: `0` is the autonomous tick, `i+1` is input `i`. -/
def tick {k : Nat} : Option (Fin k) → Fin (k + 1)
  | none => 0
  | some i => i.succ

def specSys : DiscreteSystem (Fin 8) (Fin 3) (Fin 2) where
  sz_nonempty := ⟨0⟩
  NZ x oi := specNext x (tick oi)
  RZ := specOut

def implSys : DiscreteSystem (Fin 16) (Fin 3) (Fin 2) where
  sz_nonempty := ⟨0⟩
  NZ x oi := implNext x (tick oi)
  RZ := implOut

/-! ## The maps the solver returned -/

def hS : Fin 16 → Fin 8 :=
  fun i => [
    0, 0, 1, 1, 2, 2, 3, 3,
    4, 4, 5, 5, 6, 6, 7, 7
  ].getD i.val 0

def hI : Fin 3 → Fin 3 :=
  fun i => [
    0, 1, 2
  ].getD i.val 0

def hO : Fin 2 → Fin 2 :=
  fun i => [
    0, 1
  ].getD i.val 0

/-! ## Kernel-checked conformance -/

theorem hS_surjective : Function.Surjective hS := by decide
theorem hI_surjective : Function.Surjective hI := by decide
theorem hO_surjective : Function.Surjective hO := by decide

theorem preserves_transition :
    ∀ x oi, hS (implSys.NZ x oi) = specSys.NZ (hS x) (oi.map hI) := by decide

theorem preserves_readout : ∀ x, (implSys.RZ x).map hO = specSys.RZ (hS x) := by decide

/-- The solver's model, assembled into a Definition 4.3 witness. -/
def witness : HomomorphicImageWitness specSys implSys where
  HS := hS
  HI := hI
  HO := hO
  HS_surjective := hS_surjective
  HI_surjective := hI_surjective
  HO_surjective := hO_surjective
  preserves_transition := preserves_transition
  preserves_readout := preserves_readout

/--
The verdict the solver reported, now a theorem: the candidate satisfies the fragment compiled from
the reference.
-/
theorem solver_verdict_confirmed :
    SystemSatisfiesPartialDynamicsHom specSys implSys :=
  partialDynamicsHom_of_hom ⟨witness⟩

end SolverWitness
