import Mbse.Wymore
import Mbse.WymoreCouplingStructure
import Mbse.NestedCoupling
import Mbse.Isomorphism
import Mbse.Homomorphism

/-!
# Wymore Chapter 7: technology and buildability

Typed reconstruction of Defs 7.4–7.38 and Thms 7.25–7.36 from
`wymore-defs-n-proofs-n-exercises-chp7.txt`.

**Encoding policy.** Book technologies are nonempty subsets of DSYSTEMS. Lean systems
are typed `DiscreteSystem SZ IZ OZ`, so membership is packaged via
`AnyDiscreteSystem` (intentional; faithful-with-notes — parallel to Option NZ/RZ /
`IsResultantOf`). VSCR ⊆ TYR means every component embeds as a technology member.

**Recovered definition.** “Closed under copying” is used by Thm 7.25 / Ex 7.85–86 but
absent from the extract; recovered as the COPY-analogue of Def 7.9.
-/

namespace WymoreTechnology

open Classical
open Homomorphism
open Mbse.Wymore

/-! ## Bundled systems (encoding of DSYSTEMS) -/

/--
  Bundle of a discrete system with its type parameters — Lean stand-in for an
  element of the untyped book universe DSYSTEMS.

  The `name` field distinguishes book-style “fresh copies” that are
  definitionally isomorphic but set-theoretically distinct (Ex 7.86 / Thm 7.25).
  Ordinary wrapping uses `name = 0` via `AnyDiscreteSystem.of`.
-/
structure AnyDiscreteSystem where
  SZ : Type
  IZ : Type
  OZ : Type
  Z : DiscreteSystem SZ IZ OZ
  name : Nat := 0

/-- Wrap a concrete system as an `AnyDiscreteSystem` (canonical name `0`). -/
def AnyDiscreteSystem.of {SZ IZ OZ : Type} (Z : DiscreteSystem SZ IZ OZ) :
    AnyDiscreteSystem :=
  ⟨SZ, IZ, OZ, Z, 0⟩

/-- Named wrap: used to realize infinitely many distinct isomorphic copies. -/
def AnyDiscreteSystem.ofNamed {SZ IZ OZ : Type} (n : Nat)
    (Z : DiscreteSystem SZ IZ OZ) : AnyDiscreteSystem :=
  ⟨SZ, IZ, OZ, Z, n⟩

theorem AnyDiscreteSystem.ofNamed_ne {SZ IZ OZ : Type}
    (Z : DiscreteSystem SZ IZ OZ) {n m : Nat} (hne : n ≠ m) :
    AnyDiscreteSystem.ofNamed n Z ≠ AnyDiscreteSystem.ofNamed m Z := by
  intro h
  exact hne (congrArg AnyDiscreteSystem.name h)
/-! ## Definition 7.4 / 7.7 / 7.14 — technology -/

/--
  [textbook/definition7.4/definition/technology]
  A technology is a nonempty set of (bundled) systems.
  Lives in `Type 1` because `AnyDiscreteSystem` packages `Type` parameters.
-/
def Technology : Type 1 :=
  { T : Set AnyDiscreteSystem // T.Nonempty }

/-- Carrier set of a technology. -/
def Technology.carrier (TYR : Technology) : Set AnyDiscreteSystem :=
  TYR.1

/-- Nonemptiness of a technology. -/
theorem Technology.nonempty (TYR : Technology) : TYR.carrier.Nonempty :=
  TYR.2

/--
  [textbook/definition7.4/definition/mem_technology]
  System `Z` belongs to technology `TYR` (some fresh-name wrap of `Z` is in the carrier).
-/
def memTechnology {SZ IZ OZ : Type} (TYR : Technology) (Z : DiscreteSystem SZ IZ OZ) :
    Prop :=
  ∃ n, AnyDiscreteSystem.ofNamed n Z ∈ TYR.carrier

theorem memTechnology_of {SZ IZ OZ : Type} (TYR : Technology)
    (Z : DiscreteSystem SZ IZ OZ) (h : AnyDiscreteSystem.of Z ∈ TYR.carrier) :
    memTechnology TYR Z :=
  ⟨0, h⟩

theorem memTechnology_ofNamed {SZ IZ OZ : Type} (TYR : Technology)
    (Z : DiscreteSystem SZ IZ OZ) (n : Nat)
    (h : AnyDiscreteSystem.ofNamed n Z ∈ TYR.carrier) :
    memTechnology TYR Z :=
  ⟨n, h⟩

/--
  Recovered packaging of set-theoretic “mint a fresh copy”: if `Z` is in `TYR`, every
  named wrap `ofNamed n Z` is in the carrier. Together with `ClosedUnderCopying`, this
  is the Lean reading of book closure under copying (Ex 7.86 / Thm 7.25).
-/
def ClosedUnderNaming (TYR : Technology) : Prop :=
  ∀ {SZ IZ OZ : Type} (Z : DiscreteSystem SZ IZ OZ) (n : Nat),
    memTechnology TYR Z → AnyDiscreteSystem.ofNamed n Z ∈ TYR.carrier

/-- Build a technology from a nonempty carrier. -/
def Technology.mk (T : Set AnyDiscreteSystem) (h : T.Nonempty) : Technology :=
  ⟨T, h⟩

/-- Singleton technology generated by one system. -/
def Technology.singleton {SZ IZ OZ : Type} (Z : DiscreteSystem SZ IZ OZ) : Technology :=
  Technology.mk {AnyDiscreteSystem.of Z} ⟨AnyDiscreteSystem.of Z, rfl⟩

/--
  [textbook/definition7.7/definition/finite_technology]
  Technology TYR is finite iff its carrier is a finite set.
-/
def IsFiniteTechnology (TYR : Technology) : Prop :=
  TYR.carrier.Finite

/--
  [textbook/definition7.14/definition/subtechnology]
  TYR1 is a subtechnology of TYR2 iff TYR1 ⊆ TYR2 as carriers.
-/
def IsSubtechnology (TYR1 TYR2 : Technology) : Prop :=
  TYR1.carrier ⊆ TYR2.carrier

/-- Subtechnology transports membership. -/
theorem memTechnology_of_subtechnology {SZ IZ OZ : Type}
    {TYR1 TYR2 : Technology} (hsub : IsSubtechnology TYR1 TYR2)
    (Z : DiscreteSystem SZ IZ OZ) (h : memTechnology TYR1 Z) :
    memTechnology TYR2 Z := by
  obtain ⟨n, hn⟩ := h
  exact ⟨n, hsub hn⟩

/-! ## Definition 7.9 / recovered copying / 7.12 — closure predicates -/

/--
  [textbook/definition7.9/definition/closed_under_isomorphism]
  TYR is closed under isomorphism: isomorphic systems of members remain in TYR.
-/
def ClosedUnderIsomorphism (TYR : Technology) : Prop :=
  ∀ {SZ IZ OZ SZ' IZ' OZ' : Type}
    (Z : DiscreteSystem SZ IZ OZ) (Z' : DiscreteSystem SZ' IZ' OZ'),
    memTechnology TYR Z → IsIsomorphicTo Z Z' → memTechnology TYR Z'

/--
  [textbook/definition7.9b/definition/closed_under_copying]
  Recovered from usage (Thm 7.25, Ex 7.85–86): if `Z ∈ TYR` and `Z'` is a copy of `Z`,
  then `Z' ∈ TYR`.
-/
def ClosedUnderCopying (TYR : Technology) : Prop :=
  ∀ {SZ1 SZ2 : Type} {Port1 Port2 OutPort1 OutPort2 : Type}
    {PortVal1 : Port1 → Type} {PortVal2 : Port2 → Type}
    {OutPortVal1 : OutPort1 → Type} {OutPortVal2 : OutPort2 → Type}
    (Z1 : DiscreteSystem SZ1 ((p : Port1) → PortVal1 p) ((q : OutPort1) → OutPortVal1 q))
    (Z2 : DiscreteSystem SZ2 ((p : Port2) → PortVal2 p) ((q : OutPort2) → OutPortVal2 q)),
    memTechnology TYR Z1 → IsCopyOf Z1 Z2 → memTechnology TYR Z2

/--
  [textbook/definition7.12/definition/closed_under_pure_feedback]
  OCR lock (`clsed`): if SCR is pure feedback and every component is in TYR, then
  `RSY(SCR) ∈ TYR`. (Book writes `VSCR = Z ∈ TYR` for the unique component.)
-/
def ClosedUnderPureFeedback (TYR : Technology) : Prop :=
  ∀ {n : Nat} (SCR : SystemCouplingRecipe n)
    (hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k)),
    IsPureFeedback SCR →
    (∀ i, memTechnology TYR (SCR.VSCR.Z i)) →
    memTechnology TYR (rsy SCR hOut)

/-! ## Definition 7.17 / 7.19 — buildability -/

/--
  [textbook/definition7.17/requirement/vscr_subseteq_tyr]
  Every component of `VSCR` belongs to the technology.
-/
def VSCRSubsetTechnology {n : Nat} (VSCR : PortSystemVector n) (TYR : Technology) : Prop :=
  ∀ i, memTechnology TYR (VSCR.Z i)

/--
  [textbook/definition7.17/definition/buildable]
  `Z` is buildable in `TYR` with respect to `SCR` when `VSCR ⊆ TYR` and `Z = RSY(SCR)`.
-/
def IsBuildableWith {n : Nat} {SZ IZ OZ : Type}
    (TYR : Technology) (SCR : SystemCouplingRecipe n)
    (hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k))
    (Z : DiscreteSystem SZ IZ OZ) : Prop :=
  VSCRSubsetTechnology SCR.VSCR TYR ∧ IsResultantOf Z SCR hOut

/-- Existential buildability (some recipe witnesses). -/
def IsBuildable {SZ IZ OZ : Type} (TYR : Technology) (Z : DiscreteSystem SZ IZ OZ) : Prop :=
  ∃ (n : Nat) (SCR : SystemCouplingRecipe n) (hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k)),
    IsBuildableWith TYR SCR hOut Z

/--
  [textbook/definition7.17/definition/buildable_system_design]
  Buildable system design: pair `(Z, SCR)` with `Z = BLD(TYR, SCR)`.
-/
structure BuildableSystemDesign (TYR : Technology) where
  n : Nat
  SCR : SystemCouplingRecipe n
  hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k)
  SZ : Type
  IZ : Type
  OZ : Type
  Z : DiscreteSystem SZ IZ OZ
  buildable : IsBuildableWith TYR SCR hOut Z

/--
  [textbook/definition7.19/definition/bld]
  BLD parameterizes buildable systems: `((TYR, SCR), Z)` with VSCR ⊆ TYR and Z = RSY(SCR).
-/
def BLD {n : Nat} {SZ IZ OZ : Type}
    (TYR : Technology) (SCR : SystemCouplingRecipe n)
    (hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k))
    (Z : DiscreteSystem SZ IZ OZ) : Prop :=
  IsBuildableWith TYR SCR hOut Z

/-! ## Definition 7.22 — concurrent buildability -/

/-- Component carrier of a recipe, as bundled systems (canonical name `0`). -/
def componentSet {n : Nat} (SCR : SystemCouplingRecipe n) : Set AnyDiscreteSystem :=
  { a | ∃ k, AnyDiscreteSystem.of (SCR.VSCR.Z k) = a }

/-- Named component carrier — used for concurrent families with disjoint fresh copies. -/
def componentSetNamed {n : Nat} (name : Nat) (SCR : SystemCouplingRecipe n) :
    Set AnyDiscreteSystem :=
  { a | ∃ k, AnyDiscreteSystem.ofNamed name (SCR.VSCR.Z k) = a }

/--
  [textbook/definition7.22/definition/concurrently_buildable]
  Finite family of recipes is concurrently buildable in `TYR` when each VSCR ⊆ TYR
  and distinct members use disjoint *named* component sets (fresh copies; no shared
  technology member).
-/
def ConcurrentlyBuildableFin {m : Nat} (TYR : Technology)
    (SCR : Fin m → Σ n : Nat, SystemCouplingRecipe n) : Prop :=
  (∀ i, VSCRSubsetTechnology (SCR i).2.VSCR TYR) ∧
    ∀ i j : Fin m, i ≠ j →
      Disjoint (componentSetNamed i.val (SCR i).2) (componentSetNamed j.val (SCR j).2)

/-! ## Definition 7.38 — buildability cotyledon -/

/--
  [textbook/definition7.38/definition/ctl_tyr]
  Buildability cotyledon / space generated by TYR: all buildable system designs.
-/
def CTL_TYR (TYR : Technology) : Type 1 :=
  BuildableSystemDesign TYR

/-- Alias: buildability space associated with a design problem. -/
abbrev BSR (TYR : Technology) := CTL_TYR TYR

/-! ## Tagging / copy helpers (Thm 7.25, Ex 7.86) -/

/--
  Phantom name tag: `Phantom α ≃ Unit` for every `α`, but `Phantom Nat` and `Phantom Bool`
  remain distinct types — so `SZ × Phantom n` yields isomorphic-but-distinct bundled systems.
-/
structure Phantom (α : Type) : Type where
  /-- Unique inhabitant. -/
  unit : Unit := ()

instance {α : Type} : Unique (Phantom α) where
  default := ⟨()⟩
  uniq := fun ⟨u⟩ => by cases u; rfl

instance {α : Type} : Nonempty (Phantom α) := ⟨default⟩

/-- Equivalence `SZ × Phantom α ≃ SZ`. -/
def prodPhantomEquiv (SZ : Type) (α : Type) : SZ × Phantom α ≃ SZ where
  toFun := Prod.fst
  invFun := fun s => (s, default)
  left_inv := fun ⟨s, p⟩ => by
    cases p with
    | mk u => cases u; rfl
  right_inv := fun _ => rfl

/-- Retag state space by a phantom name, preserving dynamics. -/
def tagStateSystem {SZ IZ OZ α : Type}
    (Z : DiscreteSystem SZ IZ OZ) : DiscreteSystem (SZ × Phantom α) IZ OZ where
  sz_nonempty := ⟨(Classical.choice Z.sz_nonempty, default)⟩
  NZ := fun sa oi => (Z.NZ sa.1 oi, sa.2)
  RZ := fun sa => Z.RZ sa.1

/-- Homomorphic-image witness: `Z` is the image of its phantom retagging. -/
def tagStateHom {SZ IZ OZ α : Type} (Z : DiscreteSystem SZ IZ OZ) :
    HomomorphicImageWitness Z (tagStateSystem (α := α) Z) where
  HS := Prod.fst
  HI := id
  HO := id
  HS_surjective := fun s => ⟨(s, default), rfl⟩
  HI_surjective := Function.surjective_id
  HO_surjective := Function.surjective_id
  preserves_transition := by
    intro x oi
    simp [tagStateSystem]
  preserves_readout := by
    intro x
    simp [tagStateSystem]

/-- Isomorphism: phantom-tagged system ≅ original (`Phantom α` is unique). -/
def tagStateIso {SZ IZ OZ α : Type} (Z : DiscreteSystem SZ IZ OZ) :
    IsomorphismWitness Z (tagStateSystem (α := α) Z) where
  toHomomorphicImageWitness := tagStateHom Z
  HS_injective := by
    intro sa sb h
    exact (prodPhantomEquiv SZ α).injective h
  HI_injective := Function.injective_id
  HO_injective := Function.injective_id

/-- Ported retagging used for `IsCopyOf`. -/
def tagPortedSystem {SZ Port OutPort α : Type}
    {PortVal : Port → Type} {OutPortVal : OutPort → Type}
    (Z : DiscreteSystem SZ ((p : Port) → PortVal p) ((q : OutPort) → OutPortVal q)) :
    DiscreteSystem (SZ × Phantom α) ((p : Port) → PortVal p) ((q : OutPort) → OutPortVal q) :=
  tagStateSystem (α := α) Z

/-- Copy witness for phantom retagging of a ported system. -/
def tagPortedCopy {SZ Port OutPort α : Type}
    {PortVal : Port → Type} {OutPortVal : OutPort → Type}
    (Z : DiscreteSystem SZ ((p : Port) → PortVal p) ((q : OutPort) → OutPortVal q)) :
    CopyWitness Z (tagPortedSystem (α := α) Z) where
  toIsomorphismWitness := tagStateIso Z
  inIdx := Equiv.refl Port
  outIdx := Equiv.refl OutPort
  inPorts := PreservesPorts.id
  outPorts := PreservesPorts.id

/-! ## Easy theorems / exercise anchors -/

/--
  [textbook/exercise7.85/theorem/iso_implies_copying]
  Closure under isomorphism implies closure under copying.
-/
theorem closedUnderIsomorphism_implies_closedUnderCopying (TYR : Technology)
    (h : ClosedUnderIsomorphism TYR) : ClosedUnderCopying TYR := by
  intro SZ1 SZ2 Port1 Port2 OutPort1 OutPort2 PortVal1 PortVal2 OutPortVal1 OutPortVal2 Z1 Z2 hmem hcopy
  exact h Z1 Z2 hmem hcopy.isIsomorphicTo

/--
  [textbook/exercise7.87/theorem/buildable_monotonic]
  If TYR1 ⊆ TYR2 and Z is buildable in TYR1 w.r.t. SCR, then it is buildable in TYR2.
-/
theorem buildable_of_subtechnology {n : Nat} {SZ IZ OZ : Type}
    {TYR1 TYR2 : Technology} (hsub : IsSubtechnology TYR1 TYR2)
    (SCR : SystemCouplingRecipe n) (hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k))
    (Z : DiscreteSystem SZ IZ OZ)
    (h : IsBuildableWith TYR1 SCR hOut Z) :
    IsBuildableWith TYR2 SCR hOut Z :=
  ⟨fun i => memTechnology_of_subtechnology hsub _ (h.1 i), h.2⟩

/-- Components of a buildable recipe lie in the technology. -/
theorem components_mem_of_buildable {n : Nat} {SZ IZ OZ : Type}
    {TYR : Technology} (SCR : SystemCouplingRecipe n)
    (hOut : ∀ k, AlwaysOutputs (SCR.VSCR.Z k))
    (Z : DiscreteSystem SZ IZ OZ)
    (h : IsBuildableWith TYR SCR hOut Z) :
    ∀ i, memTechnology TYR (SCR.VSCR.Z i) :=
  h.1

/--
  [textbook/exercise7.92/theorem/bsr_monotonic]
  Subtechnology transports every buildable design.
-/
def transportBuildableDesign {TYR1 TYR2 : Technology} (hsub : IsSubtechnology TYR1 TYR2)
    (d : BuildableSystemDesign TYR1) : BuildableSystemDesign TYR2 where
  n := d.n
  SCR := d.SCR
  hOut := d.hOut
  SZ := d.SZ
  IZ := d.IZ
  OZ := d.OZ
  Z := d.Z
  buildable := buildable_of_subtechnology hsub d.SCR d.hOut d.Z d.buildable

/--
  [textbook/theorem7.36/theorem/flattened_buildable_copy]
  Flattened nested coupling of buildable components yields a buildable system
  isomorphic to the nested resultant (Ex 4.86 core).
-/
theorem flattened_buildable_isomorphic {n : Nat} (N : NestedCoupling n)
    (TYR : Technology)
    (hmem : ∀ i, ∀ j, memTechnology TYR ((N.sub i).VSCR.Z j)) :
    IsBuildableWith TYR (flatRecipe N) (flat_hOut N) (rsy (flatRecipe N) (flat_hOut N)) ∧
      IsIsomorphicTo (rsy (flatRecipe N) (flat_hOut N)) (rsy (nestRecipe N) (nest_hOut N)) := by
  refine ⟨⟨?_, IsResultantOf.of_rsy _ _⟩, ⟨flatIsomorphismWitness N⟩⟩
  intro k
  let idx := flatIdxEquiv N.toNestedComponents k
  exact hmem idx.1 idx.2

/-- Alias matching the book theorem number. -/
theorem flattened_buildable_copy {n : Nat} (N : NestedCoupling n) (TYR : Technology)
    (hmem : ∀ i, ∀ j, memTechnology TYR ((N.sub i).VSCR.Z j)) :
    IsBuildableWith TYR (flatRecipe N) (flat_hOut N) (rsy (flatRecipe N) (flat_hOut N)) ∧
      IsIsomorphicTo (rsy (flatRecipe N) (flat_hOut N)) (rsy (nestRecipe N) (nest_hOut N)) :=
  flattened_buildable_isomorphic N TYR hmem

/--
  Singular (one-component, empty connectivity) design for a technology member.
-/
theorem singular_member_buildable {SZ Port OutPort : Type}
    {PortVal : Port → Type} {OutPortVal : OutPort → Type}
    (TYR : Technology)
    (Z : DiscreteSystem SZ ((p : Port) → PortVal p) ((q : OutPort) → OutPortVal q))
    (hmem : memTechnology TYR Z)
    (hOut : AlwaysOutputs Z)
    (hOutNE : Nonempty (Σ _i : Fin 1, OutPort))
    (hInNE : Nonempty (Σ _i : Fin 1, Port)) :
    let V := portVectorOfSystem PortVal OutPortVal Z
    let SCR := singularSCR V hOutNE hInNE
    let hOut' : ∀ k, AlwaysOutputs (SCR.VSCR.Z k) := fun _ => hOut
    IsBuildableWith TYR SCR hOut' (rsy SCR hOut') := by
  intro V SCR hOut'
  refine ⟨fun i => ?_, IsResultantOf.of_rsy _ _⟩
  have : SCR.VSCR.Z i = Z := by
    have hi : i = 0 := Trajectory.fin_one_eq i 0
    subst hi
    rfl
  simpa [this] using hmem

/--
  [textbook/theorem7.25/theorem/concurrent_copies_buildable]
  Book: buildables in a technology closed under copying admit a concurrently buildable
  family of copies. Lean: if `TYR` is closed under naming (fresh copies) and each of
  `m` recipes has `VSCR ⊆ TYR`, then the same recipes are concurrently buildable when
  components are tracked under distinct names `0..m-1` (pairwise-disjoint named sets).
-/
theorem concurrent_copies_buildable {m : Nat} (TYR : Technology)
    (hname : ClosedUnderNaming TYR)
    (SCR : Fin m → Σ n : Nat, SystemCouplingRecipe n)
    (hVSCR : ∀ i, VSCRSubsetTechnology (SCR i).2.VSCR TYR) :
    ConcurrentlyBuildableFin TYR SCR ∧
      (∀ i k, AnyDiscreteSystem.ofNamed i.val ((SCR i).2.VSCR.Z k) ∈ TYR.carrier) := by
  refine ⟨⟨hVSCR, ?_⟩, ?_⟩
  · intro i j hij
    refine Set.disjoint_iff.2 ?_
    intro a ⟨⟨k, hk⟩, ⟨l, hl⟩⟩
    have hnames : (i.val : Nat) = j.val :=
      congrArg AnyDiscreteSystem.name (hk.trans hl.symm)
    exact hij (Fin.ext hnames)
  · intro i k
    exact hname ((SCR i).2.VSCR.Z k) i.val (hVSCR i k)

/-- Singleton family corollary (disjointness vacuous; no naming hyp needed). -/
theorem concurrent_copies_buildable_singleton {n : Nat} (TYR : Technology)
    (SCR : SystemCouplingRecipe n)
    (hVSCR : VSCRSubsetTechnology SCR.VSCR TYR) :
    ConcurrentlyBuildableFin (m := 1) TYR (fun _ => ⟨n, SCR⟩) := by
  refine ⟨fun _ => hVSCR, ?_⟩
  intro i j hij
  exact absurd (Trajectory.fin_one_eq i j) hij

/--
  `TYR1` is concurrently buildable in `TYR2` when a finite enumeration of recipes for
  `TYR1` members is concurrently buildable in `TYR2`.
-/
def IsConcurrentlyBuildableIn {m : Nat} (TYR1 TYR2 : Technology)
    (SCR : Fin m → Σ n : Nat, SystemCouplingRecipe n) : Prop :=
  ConcurrentlyBuildableFin TYR2 SCR ∧
    (∀ i, VSCRSubsetTechnology (SCR i).2.VSCR TYR1)

/--
  [textbook/theorem7.27/theorem/buildable_in_concurrent_subtech_copy]
  If `TYR1` is concurrently buildable in `TYR2` (via `SCR`) and `Z` is buildable in
  `TYR1` w.r.t. one of those recipes, then `Z` itself is buildable in `TYR2`.
  For ported systems, the reflexive copy witness packages the book’s “there is a copy”.
-/
theorem buildable_in_concurrent_subtech_copy {m : Nat} {SZ IZ OZ : Type}
    {TYR1 TYR2 : Technology}
    (SCR : Fin m → Σ n : Nat, SystemCouplingRecipe n)
    (hconc : IsConcurrentlyBuildableIn TYR1 TYR2 SCR)
    (i : Fin m)
    (hOut : ∀ k, AlwaysOutputs ((SCR i).2.VSCR.Z k))
    (Z : DiscreteSystem SZ IZ OZ)
    (hB : IsBuildableWith TYR1 (SCR i).2 hOut Z) :
    IsBuildable TYR2 Z := by
  have hB2 : IsBuildableWith TYR2 (SCR i).2 hOut Z :=
    ⟨fun k => hconc.1.1 i k, hB.2⟩
  exact ⟨(SCR i).1, (SCR i).2, hOut, hB2⟩

/-- Ported packaging of Thm 7.27: a copy (reflexive) is buildable in `TYR2`. -/
theorem buildable_copy_in_concurrent_subtech {m : Nat}
    {SZ Port OutPort : Type}
    {PortVal : Port → Type} {OutPortVal : OutPort → Type}
    {TYR1 TYR2 : Technology}
    (SCR : Fin m → Σ n : Nat, SystemCouplingRecipe n)
    (hconc : IsConcurrentlyBuildableIn TYR1 TYR2 SCR)
    (i : Fin m)
    (hOut : ∀ k, AlwaysOutputs ((SCR i).2.VSCR.Z k))
    (Z : DiscreteSystem SZ ((p : Port) → PortVal p) ((q : OutPort) → OutPortVal q))
    (hB : IsBuildableWith TYR1 (SCR i).2 hOut Z) :
    IsCopyOf Z Z ∧ IsBuildable TYR2 Z :=
  ⟨⟨CopyWitness.refl Z⟩,
    buildable_in_concurrent_subtech_copy SCR hconc i hOut Z hB⟩

/-- Subtechnology still transports buildability (identity copy). -/
theorem buildable_of_subtechnology_exist {SZ IZ OZ : Type}
    {TYR1 TYR2 : Technology} (hsub : IsSubtechnology TYR1 TYR2)
    (Z : DiscreteSystem SZ IZ OZ) (h : IsBuildable TYR1 Z) :
    IsBuildable TYR2 Z := by
  obtain ⟨n, SCR, hOut, hb⟩ := h
  exact ⟨n, SCR, hOut, buildable_of_subtechnology hsub SCR hOut Z hb⟩

/--
  [textbook/exercise7.86/theorem/copying_implies_infinite]
  Book: closure under copying ⇒ not finite. Lean: `ClosedUnderNaming` (fresh-name
  packaging of minting copies) + one member ⇒ carrier contains an injective `Nat`
  family ⇒ not finite.
-/
theorem closedUnderCopying_not_finite {SZ IZ OZ : Type}
    (TYR : Technology) (hname : ClosedUnderNaming TYR)
    (Z : DiscreteSystem SZ IZ OZ) (hmem : memTechnology TYR Z) :
    ¬ IsFiniteTechnology TYR := by
  intro hfin
  let f : Nat → AnyDiscreteSystem := fun n => AnyDiscreteSystem.ofNamed n Z
  have hinj : Function.Injective f := by
    intro n m hnm
    by_contra hne
    exact AnyDiscreteSystem.ofNamed_ne Z hne hnm
  have hmemf : ∀ n, f n ∈ TYR.carrier := fun n => hname Z n hmem
  have hinf : (Set.range f).Infinite := Set.infinite_range_of_injective hinj
  exact Set.not_infinite.2
    (hfin.subset fun a ha => by
      obtain ⟨n, rfl⟩ := ha
      exact hmemf n)
    hinf

/-- Alias matching exercise / JSON anchor. -/
theorem copying_implies_infinite {SZ IZ OZ : Type}
    (TYR : Technology) (hname : ClosedUnderNaming TYR)
    (Z : DiscreteSystem SZ IZ OZ) (hmem : memTechnology TYR Z) :
    ¬ IsFiniteTechnology TYR :=
  closedUnderCopying_not_finite TYR hname Z hmem

end WymoreTechnology
